"""Native C backend for AGILANG v0.6.

The backend intentionally supports a strict, well-defined subset suitable
for systems-style numerical programs and command-line tools:

* numeric/bool/string primitive declarations
* functions with typed parameters and returns
* return, assignment, if/while raw blocks, and print calls
* structs as C typedef structs
* enums as C typedef enums

Unsupported constructs fail with diagnostics rather than generating unsafe
or misleading C.
"""

from __future__ import annotations

import ast
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from .ast_nodes import AssignStmt, EnumDecl, ExprStmt, FunctionDecl, LetStmt, Program, RawBlockStmt, ReturnStmt, StructDecl, TypeAlias
from .errors import Diagnostic, SourceLocation
from .parser import parse_source
from .typechecker import typecheck_source

C_TYPES = {
    "i8": "signed char", "i16": "short", "i32": "int", "i64": "long long",
    "u8": "unsigned char", "u16": "unsigned short", "u32": "unsigned int", "u64": "unsigned long long",
    "int": "int", "f32": "float", "f64": "double", "float": "double",
    "bool": "bool", "str": "const char*", "string": "const char*",
    "void": "void", "none": "void", "any": "void*",
}
PRINTF_FORMATS = {
    "i8": "%d", "i16": "%d", "i32": "%d", "i64": "%lld",
    "u8": "%u", "u16": "%u", "u32": "%u", "u64": "%llu",
    "int": "%d", "f32": "%f", "f64": "%f", "float": "%f",
    "bool": "%d", "str": "%s", "string": "%s", "any": "%p",
}


@dataclass
class CBackendResult:
    ok: bool
    c_source: str = ""
    diagnostics: list[Diagnostic] = field(default_factory=list)

    def format(self) -> str:
        return "\n".join(d.format() for d in self.diagnostics) if self.diagnostics else "OK: C backend generated source"


class CBackend:
    def __init__(self, path: Path | None = None) -> None:
        self.path = path
        self.aliases: dict[str, str] = {}
        self.var_types_stack: list[dict[str, str]] = []
        self.fn_returns: dict[str, str] = {}
        self.diagnostics: list[Diagnostic] = []

    def generate(self, source: str) -> CBackendResult:
        type_report = typecheck_source(source, self.path)
        self.diagnostics.extend(type_report.diagnostics)
        program = parse_source(source, self.path)
        self._collect(program)
        lines = [
            "// Generated by AGILANG v0.6 native C backend.",
            "#include <stdio.h>",
            "#include <stdbool.h>",
            "#include <stdint.h>",
            "",
        ]
        for node in program.body:
            if isinstance(node, StructDecl):
                lines.extend(self._struct(node))
            elif isinstance(node, EnumDecl):
                lines.extend(self._enum(node))
        for node in program.body:
            if isinstance(node, FunctionDecl):
                lines.extend(self._function(node))
                lines.append("")
            elif isinstance(node, (LetStmt, AssignStmt, ExprStmt, RawBlockStmt)):
                self._error("EC001", "Top-level executable statements are not supported by the C backend.", node.span.line)
        ok = not any(d.severity == "error" for d in self.diagnostics)
        return CBackendResult(ok=ok, c_source="\n".join(lines).rstrip() + "\n", diagnostics=self.diagnostics)

    def _collect(self, program: Program) -> None:
        for node in program.body:
            if isinstance(node, TypeAlias):
                self.aliases[node.name] = self._ctype(node.target)
            elif isinstance(node, FunctionDecl):
                self.fn_returns[node.name] = self._ctype(node.return_type)

    def _loc(self, line: int) -> SourceLocation:
        return SourceLocation(self.path, line, 1)

    def _error(self, code: str, message: str, line: int, hint: str | None = None) -> None:
        self.diagnostics.append(Diagnostic("error", code, message, self._loc(line), hint))

    def _ctype(self, type_name: str | None) -> str:
        if not type_name:
            return "void*"
        t = type_name.strip()
        if t in self.aliases:
            return self.aliases[t]
        return C_TYPES.get(t, t)

    @property
    def vars(self) -> dict[str, str]:
        return self.var_types_stack[-1]

    def _struct(self, node: StructDecl) -> list[str]:
        lines = [f"typedef struct {node.name} {{"]
        for field in node.fields:
            lines.append(f"    {self._ctype(field.type_name)} {field.name};")
        lines.append(f"}} {node.name};")
        lines.append("")
        return lines

    def _enum(self, node: EnumDecl) -> list[str]:
        lines = [f"typedef enum {node.name} {{"]
        for i, variant in enumerate(node.variants):
            comma = "," if i < len(node.variants) - 1 else ""
            lines.append(f"    {variant}{comma}")
        lines.append(f"}} {node.name};")
        lines.append("")
        return lines

    def _function(self, node: FunctionDecl) -> list[str]:
        ret = self._ctype(node.return_type)
        params = []
        self.var_types_stack.append({})
        for p in node.params:
            ctype = self._ctype(p.type_name)
            self.vars[p.name] = p.type_name
            params.append(f"{ctype} {p.name}")
        sig = "int main(void)" if node.name == "main" and not params else f"{ret} {node.name}({', '.join(params) if params else 'void'})"
        lines = [sig + " {"]
        for stmt in node.body:
            lines.extend(self._stmt(stmt, indent=1))
        if node.name == "main" and not any(isinstance(s, ReturnStmt) for s in node.body):
            lines.append("    return 0;")
        lines.append("}")
        self.var_types_stack.pop()
        return lines

    def _stmt(self, stmt, indent: int) -> list[str]:
        pad = "    " * indent
        if isinstance(stmt, LetStmt):
            t = stmt.type_name or self._infer_expr_type(stmt.expr)
            self.vars[stmt.name] = t
            return [f"{pad}{self._ctype(t)} {stmt.name} = {self._expr(stmt.expr)};"]
        if isinstance(stmt, AssignStmt):
            return [f"{pad}{stmt.target} {stmt.op} {self._expr(stmt.expr)};"]
        if isinstance(stmt, ReturnStmt):
            return [f"{pad}return {self._expr(stmt.expr or '0')};"]
        if isinstance(stmt, ExprStmt):
            if stmt.expr.startswith("print("):
                return [pad + self._print_call(stmt.expr)]
            return [f"{pad}{self._expr(stmt.expr)};"]
        if isinstance(stmt, RawBlockStmt):
            if stmt.kind in {"if", "while"}:
                header = stmt.header[:-1] if stmt.header.endswith(":") else stmt.header
                keyword, expr = header.split(None, 1)
                lines = [f"{pad}{keyword} ({self._expr(expr)}) {{"]
                for child in stmt.body:
                    lines.extend(self._stmt(child, indent + 1))
                lines.append(f"{pad}}}")
                return lines
            if stmt.kind == "else":
                lines = [f"{pad}else {{"]
                for child in stmt.body:
                    lines.extend(self._stmt(child, indent + 1))
                lines.append(f"{pad}}}")
                return lines
            self._error("EC002", f"C backend does not yet support `{stmt.kind}` blocks.", stmt.span.line, "Use if/while blocks or run through the Python backend.")
            return [f"{pad}/* unsupported {stmt.kind} block */"]
        return [f"{pad}/* unsupported statement */"]

    def _print_call(self, expr: str) -> str:
        try:
            call = ast.parse(expr, mode="eval").body
        except SyntaxError:
            self._error("EC003", f"Invalid print expression `{expr}`.", 1)
            return 'printf("<invalid print>\\n");'
        if not isinstance(call, ast.Call):
            return f"{self._expr(expr)};"
        formats = []
        values = []
        for arg in call.args:
            if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                formats.append(str(arg.value).replace("%", "%%"))
            else:
                source = ast.unparse(arg)
                t = self._infer_node_type(arg)
                formats.append(PRINTF_FORMATS.get(t, "%p"))
                values.append(self._expr(source))
        fmt = " ".join(formats) + "\\n"
        if values:
            return f'printf("{fmt}", {", ".join(values)});'
        return f'printf("{fmt}");'

    def _expr(self, expr: str) -> str:
        try:
            tree = ast.parse(expr, mode="eval").body
        except SyntaxError:
            self._error("EC004", f"Invalid C expression `{expr}`.", 1)
            return "0"
        return self._expr_node(tree)

    def _expr_node(self, node: ast.AST) -> str:
        if isinstance(node, ast.Constant):
            if isinstance(node.value, str):
                escaped = node.value.replace('\\', '\\\\').replace('"', '\\"')
                return f'"{escaped}"'
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            if node.value is None:
                return "0"
            return repr(node.value)
        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.BinOp):
            return f"({self._expr_node(node.left)} {self._op(node.op)} {self._expr_node(node.right)})"
        if isinstance(node, ast.UnaryOp):
            return f"({self._op(node.op)}{self._expr_node(node.operand)})"
        if isinstance(node, ast.Compare):
            left = self._expr_node(node.left)
            parts = []
            for op, comp in zip(node.ops, node.comparators):
                right = self._expr_node(comp)
                parts.append(f"({left} {self._op(op)} {right})")
                left = right
            return " && ".join(parts)
        if isinstance(node, ast.BoolOp):
            op = " && " if isinstance(node.op, ast.And) else " || "
            return "(" + op.join(self._expr_node(v) for v in node.values) + ")"
        if isinstance(node, ast.Call):
            name = self._call_name(node.func)
            args = ", ".join(self._expr_node(a) for a in node.args)
            return f"{name}({args})"
        self._error("EC005", f"Unsupported C expression: {ast.dump(node)}", 1)
        return "0"

    def _op(self, op: ast.AST) -> str:
        return {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/", ast.Mod: "%", ast.Eq: "==", ast.NotEq: "!=", ast.Lt: "<", ast.LtE: "<=", ast.Gt: ">", ast.GtE: ">=", ast.USub: "-", ast.UAdd: "+", ast.Not: "!"}.get(type(op), "/*op*/")

    def _call_name(self, node: ast.AST) -> str:
        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.Attribute):
            return node.attr
        return "call"

    def _infer_expr_type(self, expr: str) -> str:
        try:
            return self._infer_node_type(ast.parse(expr, mode="eval").body)
        except Exception:
            return "i32"

    def _infer_node_type(self, node: ast.AST) -> str:
        if isinstance(node, ast.Constant):
            if isinstance(node.value, str): return "str"
            if isinstance(node.value, bool): return "bool"
            if isinstance(node.value, float): return "f64"
            if isinstance(node.value, int): return "i32"
        if isinstance(node, ast.Name):
            return self.vars.get(node.id, "i32")
        if isinstance(node, ast.BinOp):
            left = self._infer_node_type(node.left)
            right = self._infer_node_type(node.right)
            return "f64" if left in {"f32", "f64", "float"} or right in {"f32", "f64", "float"} or isinstance(node.op, ast.Div) else "i32"
        if isinstance(node, ast.Call):
            return "i32"
        return "i32"


def to_c_source(source: str, path: Path | None = None) -> CBackendResult:
    return CBackend(path).generate(source)


def to_c_file(path: Path) -> CBackendResult:
    return to_c_source(path.read_text(encoding="utf-8"), path.resolve())


def compile_c(c_file: Path, output: Path, cc: str = "gcc") -> subprocess.CompletedProcess[str]:
    compiler = shutil.which(cc)
    if compiler is None:
        raise FileNotFoundError(f"C compiler `{cc}` was not found on PATH. Install GCC/Clang or use `agilang build` for Python launcher builds.")
    output.parent.mkdir(parents=True, exist_ok=True)
    return subprocess.run([compiler, str(c_file), "-std=c11", "-O2", "-Wall", "-Wextra", "-o", str(output)], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
