// Generated by AGILANG v0.6 native C backend.
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>

int square(int x) {
    return (x * x);
}

int main(void) {
    int value = square(7);
    printf("native result %d\n", value);
    return 0;
}
